In [2]:
import pandas as pd

In [3]:
sales = pd.read_csv("../data/raw/sales_daily.csv")

In [4]:
sales.head()

         Date     SKU  Units_Sold    Revenue    Price  Promotion
0  2024-01-01  SKU001           5   18320.25  3664.05          0
1  2024-01-01  SKU002          15   57085.35  3805.69          0
2  2024-01-01  SKU003           5   40391.15  8078.23          0
3  2024-01-01  SKU004           5   34307.85  6861.57          0
4  2024-01-01  SKU005          12  113918.64  9493.22          0

In [5]:
sales.shape

(36550, 6)

In [6]:
sales.columns

Index(['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion'], dtype='str')

In [7]:
sales.dtypes

Date              str
SKU               str
Units_Sold      int64
Revenue       float64
Price         float64
Promotion       int64
dtype: object

In [8]:
sales.isnull().sum()

Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

In [9]:
sales.duplicated().sum()

np.int64(0)

In [10]:
sales['Date'].min(), sales['Date'].max()

('2024-01-01', '2025-12-31')

In [11]:
sales['SKU'].nunique()

50

In [12]:
# Convert Date from text to datetime for time-based analysis and forecasting
sales["Date"]= pd.to_datetime(sales["Date"])
sales.dtypes

Date          datetime64[us]
SKU                      str
Units_Sold             int64
Revenue              float64
Price                float64
Promotion              int64
dtype: object

In [13]:
# Checking each SKU has one sales record per day 
sales.groupby(["Date","SKU"]).size().value_counts()

1    36550
Name: count, dtype: int64

In [14]:
# Check for negative sales 
(sales["Units_Sold"] < 0).sum(), (sales["Revenue"] < 0).sum()

(np.int64(0), np.int64(0))

In [15]:
sales["SKU"].unique()

<StringArray>
['SKU001', 'SKU002', 'SKU003', 'SKU004', 'SKU005', 'SKU006', 'SKU007',
 'SKU008', 'SKU009', 'SKU010', 'SKU011', 'SKU012', 'SKU013', 'SKU014',
 'SKU015', 'SKU016', 'SKU017', 'SKU018', 'SKU019', 'SKU020', 'SKU021',
 'SKU022', 'SKU023', 'SKU024', 'SKU025', 'SKU026', 'SKU027', 'SKU028',
 'SKU029', 'SKU030', 'SKU031', 'SKU032', 'SKU033', 'SKU034', 'SKU035',
 'SKU036', 'SKU037', 'SKU038', 'SKU039', 'SKU040', 'SKU041', 'SKU042',
 'SKU043', 'SKU044', 'SKU045', 'SKU046', 'SKU047', 'SKU048', 'SKU049',
 'SKU050']
Length: 50, dtype: str

In [16]:
sales[["Units_Sold", "Revenue","Price"]].describe()

         Units_Sold       Revenue         Price
count  36550.000000   36550.00000  36550.000000
mean      14.003010   84707.43385   5892.663800
std        8.467305   76534.63044   3138.775609
min        0.000000       0.00000    663.460000
25%        7.000000   27643.70000   3484.090000
50%       13.000000   56125.90000   5649.795000
75%       20.000000  127954.32000   8516.600000
max       56.000000  546977.00000  11642.450000

In [17]:
# Count zero-sales days for each SKU
zero_sales = (sales["Units_Sold"]== 0).groupby(sales['SKU']).sum()

zero_sales.describe()

count    50.00000
mean      4.04000
std      12.28897
min       0.00000
25%       0.00000
50%       0.00000
75%       0.75000
max      58.00000
Name: Units_Sold, dtype: float64

In [18]:
zero_sales.sort_values(ascending=False).head()

SKU
SKU025    58
SKU011    55
SKU039    36
SKU015    15
SKU004    13
Name: Units_Sold, dtype: int64

In [19]:
# Check the number of recorded days for each SKU
sales.groupby("SKU")["Date"].nunique().describe()

count     50.0
mean     731.0
std        0.0
min      731.0
25%      731.0
50%      731.0
75%      731.0
max      731.0
Name: Date, dtype: float64

In [20]:
# Total units sold by SKU
sku_sales = sales.groupby("SKU")["Units_Sold"].sum().sort_values(ascending=False)

sku_sales.head(10)

SKU
SKU012    19067
SKU045    18612
SKU018    18450
SKU049    18373
SKU037    18155
SKU007    18129
SKU027    17717
SKU042    16616
SKU026    16535
SKU043    16276
Name: Units_Sold, dtype: int64

In [21]:
# Total units sold by SKU, lowest first
sku_sales.sort_values().head(10)

SKU
SKU011    1951
SKU025    1976
SKU039    2300
SKU015    2994
SKU004    3380
SKU030    3493
SKU036    3508
SKU028    4101
SKU003    4214
SKU050    4537
Name: Units_Sold, dtype: int64

In [22]:
# Compare average units sold on promotion vs non promotion days
sales.groupby("Promotion")["Units_Sold"].mean()

Promotion
0    13.475945
1    18.613067
Name: Units_Sold, dtype: float64

In [23]:
# Count promotion vs non promotion days 
sales["Promotion"].value_counts()

Promotion
0    32800
1     3750
Name: count, dtype: int64

In [24]:
sku_master = pd.read_csv("../data/raw/sku_master.csv")

In [25]:
# sku_master column names
sku_master.columns

Index(['SKU', 'Product_Name', 'Category', 'Subcategory', 'Launch_Date',
       'Cost_Price', 'Selling_Price', 'Gross_Margin_Per_Unit'],
      dtype='str')

In [26]:
# sku_master datatype
sku_master.dtypes

SKU                          str
Product_Name                 str
Category                     str
Subcategory                  str
Launch_Date                  str
Cost_Price               float64
Selling_Price            float64
Gross_Margin_Per_Unit    float64
dtype: object

In [27]:
# Checking null values
sku_master.isnull().sum()

SKU                      0
Product_Name             0
Category                 0
Subcategory              0
Launch_Date              0
Cost_Price               0
Selling_Price            0
Gross_Margin_Per_Unit    0
dtype: int64

In [29]:
# Checking duplicate values
sku_master.duplicated().sum()

np.int64(0)

In [37]:
# Checking Category Count
category_count = sku_master.groupby("Category")["SKU"].count()
print(category_count)

Category
Furniture     10
Home Decor    10
Kitchen       10
Lighting      10
Storage       10
Name: SKU, dtype: int64

In [38]:
# Checking Subcategory Count
subcategory_count = sku_master.groupby("Subcategory")["SKU"].count()
print(subcategory_count)

Subcategory
Cabinet      5
Chair        5
Cookware     5
Cushion      5
Lamp         5
Organizer    5
Rug          5
Shelf        5
Sofa         5
Table        5
Name: SKU, dtype: int64

In [41]:
# Finding SKUs Where Selling Price is Lower Than cost Price
below_cost = sku_master[
    sku_master["Selling_Price"]< sku_master["Cost_Price"]
]
print(below_cost)

       SKU Product_Name    Category Subcategory Launch_Date  Cost_Price  \
1   SKU002  Product 002  Home Decor       Table  2024-05-01     3867.09
6   SKU007  Product 007  Home Decor     Cabinet  2022-04-05     7748.20
8   SKU009  Product 009    Lighting   Organizer  2022-08-10     3121.06
9   SKU010  Product 010     Storage        Sofa  2022-04-14     3889.06
10  SKU011  Product 011   Furniture       Chair  2023-08-03     1718.40
15  SKU016  Product 016   Furniture       Shelf  2024-05-14     3637.93
17  SKU018  Product 018     Kitchen         Rug  2022-05-21     5677.05
19  SKU020  Product 020     Storage        Sofa  2023-05-11     6700.01
22  SKU023  Product 023     Kitchen     Cushion  2022-07-20     2484.54
23  SKU024  Product 024    Lighting    Cookware  2024-10-16     5539.34
27  SKU028  Product 028     Kitchen         Rug  2024-06-24     6348.66
32  SKU033  Product 033     Kitchen     Cushion  2022-04-12     4657.74
36  SKU037  Product 037  Home Decor     Cabinet  2024-08-02     3901.00
37  SKU038  Product 038     Kitchen         Rug  2024-06-29     4630.58
39  SKU040  Product 040     Storage        Sofa  2023-11-26     5169.07
47  SKU048  Product 048     Kitchen         Rug  2024-09-09     6863.87

    Selling_Price  Gross_Margin_Per_Unit
1         3805.69                 -61.40
6         5114.09               -2634.11
8         2336.89                -784.17
9          663.46               -3225.60
10        1444.56                -273.84
15        2166.82               -1471.11
17        5575.41                -101.64
19        3897.54               -2802.47
22        1416.74               -1067.80
23        1768.87               -3770.47
27        3484.09               -2864.57
32        3558.00               -1099.74
36        2747.42               -1153.58
37        3949.10                -681.48
39        2450.56               -2718.51
47        1379.55               -5484.32

In [ ]:
# Converting Launch_Date str to datetime
sku_master['Launch_Date'] = pd.to_datetime(sku_master["Launch_Date"])
sku_master.dtypes

SKU                                 str
Product_Name                        str
Category                            str
Subcategory                         str
Launch_Date              datetime64[us]
Cost_Price                      float64
Selling_Price                   float64
Gross_Margin_Per_Unit           float64
dtype: object

In [ ]:
# Checking All SKUs Whose launch date > last date in our sales data
sku_master[sku_master["Launch_Date"]> pd.Timestamp("2025-12-31")]

Empty DataFrame
Columns: [SKU, Product_Name, Category, Subcategory, Launch_Date, Cost_Price, Selling_Price, Gross_Margin_Per_Unit]
Index: []

In [47]:
# checking SKUs has a future launch date relative to the beginning of the sales period
sku_master[sku_master["Launch_Date"]< pd.Timestamp("2024-01-01")]

,SKU,Product_Name,Category,Subcategory,Launch_Date,Cost_Price,Selling_Price,Gross_Margin_Per_Unit
0,SKU001,Product 001,Furniture,Chair,2022-04-09,1758.45,3664.05,1905.60
2,SKU003,Product 003,Kitchen,Cushion,2023-12-22,589.48,8078.23,7488.75
3,SKU004,Product 004,Lighting,Cookware,2023-04-28,1445.74,6861.57,5415.83
4,SKU005,Product 005,Storage,Lamp,2023-04-22,5543.63,9493.22,3949.59
6,SKU007,Product 007,Home Decor,Cabinet,2022-04-05,7748.20,5114.09,-2634.11
8,SKU009,Product 009,Lighting,Organizer,2022-08-10,3121.06,2336.89,-784.17
9,SKU010,Product 010,Storage,Sofa,2022-04-14,3889.06,663.46,-3225.60
10,SKU011,Product 011,Furniture,Chair,2023-08-03,1718.40,1444.56,-273.84
16,SKU017,Product 017,Home Decor,Cabinet,2023-07-19,6703.26,8477.32,1774.06
17,SKU018,Product 018,Kitchen,Rug,2022-05-21,5677.05,5575.41,-101.64
19,SKU020,Product 020,Storage,Sofa,2023-05-11,6700.01,3897.54,-2802.47
20,SKU021,Product 021,Furniture,Chair,2023-07-05,6486.92,7711.28,1224.36
21,SKU022,Product 022,Home Decor,Table,2023-02-12,3252.96,4597.03,1344.07
22,SKU023,Product 023,Kitchen,Cushion,2022-07-20,2484.54,1416.74,-1067.80
25,SKU026,Product 026,Furniture,Shelf,2023-12-10,1799.29,10939.54,9140.25
26,SKU027,Product 027,Home Decor,Cabinet,2023-03-19,307.06,8516.60,8209.54
28,SKU029,Product 029,Lighting,Organizer,2023-08-23,5402.59,11642.45,6239.86
29,SKU030,Product 030,Storage,Sofa,2023-05-03,5715.03,9433.51,3718.48
30,SKU031,Product 031,Furniture,Chair,2023-05-11,6300.65,8715.93,2415.28
31,SKU032,Product 032,Home Decor,Table,2022-09-07,3806.60,5612.59,1805.99
32,SKU033,Product 033,Kitchen,Cushion,2022-04-12,4657.74,3558.00,-1099.74
33,SKU034,Product 034,Lighting,Cookware,2023-09-03,1333.43,1518.14,184.71
35,SKU036,Product 036,Furniture,Shelf,2022-03-12,5430.12,5687.00,256.88
38,SKU039,Product 039,Lighting,Organizer,2022-11-01,6178.74,7118.95,940.21
39,SKU040,Product 040,Storage,Sofa,2023-11-26,5169.07,2450.56,-2718.51
40,SKU041,Product 041,Furniture,Chair,2022-07-01,4540.24,10336.73,5796.49
43,SKU044,Product 044,Lighting,Cookware,2023-01-25,488.84,5412.28,4923.44
44,SKU045,Product 045,Storage,Lamp,2022-03-16,3634.56,7676.78,4042.22
46,SKU047,Product 047,Home Decor,Cabinet,2023-05-06,3416.10,7938.22,4522.12

In [48]:
# Check whether Gross Margin is calculated correctly
expected_margin = sku_master["Selling_Price"] - sku_master["Cost_Price"]

# Find rows where the stored margin doesn't match the calculated margin
margin_check = sku_master[
    abs(expected_margin - sku_master["Gross_Margin_Per_Unit"]) > 0.01
]

print(margin_check)
print("Number of inconsistent rows:", len(margin_check))

Empty DataFrame
Columns: [SKU, Product_Name, Category, Subcategory, Launch_Date, Cost_Price, Selling_Price, Gross_Margin_Per_Unit]
Index: []
Number of inconsistent rows: 0